# Generated by update-img-hashes.sh; do not edit by hand.
{
  version = "2.35.1";
  hashes = [
    {
      name = "z01";
      hash = "sha256-/OLHJKtCOmC7upRJX9IZLyMYh5UPGMQrJoDZnHBJw0M=";
    }
    {
      name = "z02";
      hash = "sha256-hwc4sbqUkDqSArTCX0uDzRxdau7h63EJf7GUuJGjj9s=";
    }
    {
      name = "z03";
      hash = "sha256-sxAWTHvcJFCkR7azyVoiNCSCFt1UwXQYZV5EzdlzDSM=";
    }
    {
      name = "z04";
      hash = "sha256-VcZEqeJanvqUe+yFzMne4J/eZIKUKjNVnh7POt/3Lj8=";
    }
    {
      name = "z05";
      hash = "sha256-W4RvMmEB6r/M0BjRDIlCUeoRfCTJaG9TsMQrR/wtZSA=";
    }
    {
      name = "z06";
      hash = "sha256-Vf1e7j/HnUc1LoMvgUr8Pf4bQjhmtE2TQNcfhdXNNko=";
    }
    {
      name = "z07";
      hash = "sha256-H0ErP5W63anSvRcWKNzYZxlhr2C4g7lDD8SJU4+eC90=";
    }
    {
      name = "z08";
      hash = "sha256-fMCSfgysbWjOLC4hUQjfoa4hm6RS9AVO3DOOAEV0PX4=";
    }
    {
      name = "z09";
      hash = "sha256-sXCnHiCy9kFyy0QhGS4o5ephpwdatIsNnAHsX0SiFkg=";
    }
    {
      name = "z10";
      hash = "sha256-rJ7SqkSxrZkAC8DfAmLXdg+ubhjCpgvc36jcs0eYph0=";
    }
    {
      name = "z11";
      hash = "sha256-rgGomkBxx4GaW68Zflp2iISCrkXfex0QR4hyPyZDx4Q=";
    }
    {
      name = "z12";
      hash = "sha256-dagj1NHB0ikGiTbX10ojSvA+BZxpzIZjLq5D04zECCQ=";
    }
    {
      name = "zip";
      hash = "sha256-8NPNaE7iBxqExdCUhjf5ebxe4Bjm/KlQ8o6b1tDuUSs=";
    }
  ];
}
